### ISSUE TITLE
Cargo package

### ISSUE THREAD

**Issue by l1x** [litchipi/mdtrans#1]
Hi,

Are you publishing this as a Cargo package?

**Comment by litchipi** [comment]
Yeah sure why not ? I'll work on it during the week

**Comment by litchipi** [comment]
Done, the package is available here: https://crates.io/crates/mdtrans

Feel free to open issues if you need some features, or even a PR if you wish to contribute ! :-)

**Comment by l1x** [comment]
Thanks a lot!
